"""Anomaly and risk detection alerts for Roof Smart Finance."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Literal

import pandas as pd
from rich.console import Console

console = Console()
logger = logging.getLogger(__name__)

AlertLevel = Literal["CRITICAL", "WARNING", "INFO"]


@dataclass
class Alert:
    """A single alert generated by the alerts engine."""
    level: AlertLevel
    title: str
    detail: str
    icon: str = ""

    def __post_init__(self):
        if not self.icon:
            self.icon = {"CRITICAL": "🔴", "WARNING": "🟡", "INFO": "🟢"}.get(self.level, "⚪")

    def to_dict(self) -> dict:
        return {"level": self.level, "icon": self.icon, "title": self.title, "detail": self.detail}


def generate_alerts(df: pd.DataFrame) -> list[Alert]:
    """Run all alert checks and return sorted list of alerts."""
    if df.empty:
        return [Alert("INFO", "No Data", "No transactions loaded yet.")]

    alerts: list[Alert] = []
    df = df.copy()
    df["_date"] = pd.to_datetime(df["date"], errors="coerce")
    df["_abs"] = df["amount"].abs()

    # ── CRITICAL Alerts ──────────────────────────────────────────────────────

    # Low balance per account
    df_valid = df[df["balance"] > 0]
    if not df_valid.empty:
        latest_balance = (
            df_valid.sort_values("_date")
            .groupby("account_last4")["balance"]
            .last()
        )
        for account, bal in latest_balance.items():
            if bal < 5_000:
                alerts.append(Alert(
                    "CRITICAL",
                    f"Low Balance: Account ...{account}",
                    f"Account ending {account} balance is ${bal:,.2f} — below $5,000 threshold.",
                ))

    # Large unknown vendor charges
    large_unknown = df[
        (df["category"] == "UNKNOWN") &
        (df["amount"] < -10_000)
    ]
    for _, row in large_unknown.iterrows():
        alerts.append(Alert(
            "CRITICAL",
            "Large Unknown Charge",
            f"${abs(row['amount']):,.2f} on {row['date']} to unknown vendor: {row['description'][:60]}",
        ))

    # ── WARNING Alerts ───────────────────────────────────────────────────────

    # Monthly expense spike >15%
    expense_df = df[df["amount"] < 0].copy()
    if not expense_df.empty:
        expense_df["month"] = expense_df["_date"].dt.to_period("M").astype(str)
        monthly_exp = expense_df.groupby("month")["amount"].sum().abs().sort_index()
        if len(monthly_exp) >= 2:
            months = monthly_exp.index.tolist()
            for i in range(1, len(months)):
                prev = monthly_exp.iloc[i - 1]
                curr = monthly_exp.iloc[i]
                if prev > 0 and (curr - prev) / prev > 0.15:
                    pct = round((curr - prev) / prev * 100, 1)
                    alerts.append(Alert(
                        "WARNING",
                        "Expense Spike",
                        f"Expenses in {months[i]} increased {pct}% vs prior month (${curr:,.0f} vs ${prev:,.0f})",
                    ))

    # No revenue for 7+ consecutive business days
    revenue_df = df[df["category"] == "REVENUE"].copy()
    if not revenue_df.empty:
        revenue_dates = sorted(revenue_df["_date"].dropna().dt.date.unique())
        if revenue_dates:
            last_revenue = revenue_dates[-1]
            days_since = (datetime.now().date() - last_revenue).days
            if days_since >= 7:
                alerts.append(Alert(
                    "WARNING",
                    "No Recent Revenue",
                    f"No revenue deposits detected in the last {days_since} days (last: {last_revenue})",
                ))

    # Duplicate transaction (same amount within 3 days, same account)
    df_sorted = df.sort_values(["account_last4", "amount", "_date"])
    for _, group in df_sorted.groupby(["account_last4", "amount"]):
        if len(group) < 2:
            continue
        dates = group["_date"].dropna().sort_values()
        for i in range(1, len(dates)):
            if (dates.iloc[i] - dates.iloc[i - 1]).days <= 3:
                row = group.iloc[i]
                alerts.append(Alert(
                    "WARNING",
                    "Possible Duplicate Transaction",
                    f"${abs(row['amount']):,.2f} on {row['date']} appears twice within 3 days: {row['description'][:50]}",
                ))
                break  # One alert per group

    # New subscription charges
    current_month = datetime.now().strftime("%Y-%m")
    prior_months_df = df[df["_date"].dt.to_period("M").astype(str) < current_month]
    current_month_df = df[df["_date"].dt.to_period("M").astype(str) == current_month]

    sub_keywords = ["subscription", "monthly", "annual", "recurring", "auto-pay", "saas"]
    prior_subs = set(
        prior_months_df[
            prior_months_df["description"].str.lower().str.contains("|".join(sub_keywords), na=False)
        ]["description"].str[:30].str.lower().unique()
    )
    curr_subs = current_month_df[
        current_month_df["description"].str.lower().str.contains("|".join(sub_keywords), na=False)
    ]
    for _, row in curr_subs.iterrows():
        key = row["description"][:30].lower()
        if key not in prior_subs:
            alerts.append(Alert(
                "WARNING",
                "New Recurring Charge",
                f"First-time subscription detected: {row['description'][:60]} (${abs(row['amount']):,.2f})",
            ))

    # ── INFO Alerts ──────────────────────────────────────────────────────────

    # Largest single revenue deposit
    revenue_only = df[df["category"] == "REVENUE"]
    if not revenue_only.empty:
        largest = revenue_only.loc[revenue_only["amount"].idxmax()]
        alerts.append(Alert(
            "INFO",
            "Largest Revenue Deposit",
            f"${largest['amount']:,.2f} on {largest['date']}: {largest['description'][:60]}",
        ))

    # Month with highest net cash position
    expense_all = df[df["amount"] < 0].copy()
    income_all = df[df["amount"] > 0].copy()
    if not expense_all.empty and not income_all.empty:
        expense_all["month"] = expense_all["_date"].dt.to_period("M").astype(str)
        income_all["month"] = income_all["_date"].dt.to_period("M").astype(str)
        monthly_net = (
            income_all.groupby("month")["amount"].sum() +
            expense_all.groupby("month")["amount"].sum()
        ).dropna()
        if not monthly_net.empty:
            best_month = monthly_net.idxmax()
            best_val = monthly_net.max()
            alerts.append(Alert(
                "INFO",
                "Best Cash Month",
                f"{best_month} was your strongest month with +${best_val:,.2f} net cash position.",
            ))

    # Sort: CRITICAL → WARNING → INFO
    order = {"CRITICAL": 0, "WARNING": 1, "INFO": 2}
    alerts.sort(key=lambda a: order.get(a.level, 99))
    return alerts
